### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by Rene-63** [Mmtrx/FS25_BetterContracts#86]
Once in de contract menu, it's impossible to leave the menu.
When this script is deleted from the mods directory, there is no more issue, so I conclude the script is the reason of the issue.

I:/OneDrive/Documenten/My Games/FarmingSimulator2025/mods/FS25_RefreshContracts/RefreshContracts.lua:54: attempt to index number with 'unlinkElement'
2025-05-10 12:41:07 Error: Running LUA method 'update'.
I:/OneDrive/Documenten/My Games/FarmingSimulator2025/mods/FS25_RefreshContracts/RefreshContracts.lua:54: attempt to index number with 'unlinkElement'
2025-05-10 12:41:12 Error: Running LUA method 'mouseEvent'.

**Comment by Mmtrx** [comment]
It's a compatibility issue with RefreshContracts, see #72. Will be fixed with next version of BC.

**Comment by Mmtrx** [comment]
Done, see [v1.1.2.0](https://github.com/Mmtrx/FS25_BetterContracts/releases/tag/v1.1.2.0)

**Comment by Rene-63** [comment]
I'm sorry, but the problem is still the same.
I think there is a problem with the map

![Image](https://github.com/user-attachments/assets/e290b3d4-f526-4203-b811-37400d736f58)

**Comment by Mmtrx** [comment]
Hm, your screen format looks strange, I don't think that is 16:9.
What happens if you don't load FS25_RefreshContracts mod?
And could you upload your complete log.txt please?

**Comment by Rene-63** [comment]
[log.txt](https://github.com/user-attachments/files/20418380/log.txt)

The screenformat is indeed strange, because I did  made it smaller for the moment to 1920x1080 (16:9). The format screenshot happend by pasting in github
Normally its full screen 3440 x 1440 (21:9)

Without FS25_RefreshContracts mod it's working fine.

**Comment by Mmtrx** [comment]
Ok, and you don't need RefreshContracts, because BC includes that function 😉
